0 0 dataAuditErrors
1 0 non45Errors
2 0 offGridErrors
75 0 offGridShapeErrors: off grid polygon on layer BJTdum
78 0 offGridShapeErrors: off grid polygon on layer Bondpad
81 0 offGridShapeErrors: off grid polygon on layer CapMetal
84 0 offGridShapeErrors: off grid polygon on layer Cont
87 0 offGridShapeErrors: off grid polygon on layer IND2dummy
90 0 offGridShapeErrors: off grid polygon on layer IND3dummy
93 0 offGridShapeErrors: off grid polygon on layer INDdummy
96 0 offGridShapeErrors: off grid polygon on layer JVAR1dummy
99 0 offGridShapeErrors: off grid polygon on layer JVAR2dummy
102 0 offGridShapeErrors: off grid polygon on layer JVAR3dummy
105 0 offGridShapeErrors: off grid polygon on layer M1dummy
108 0 offGridShapeErrors: off grid polygon on layer M2dummy
111 0 offGridShapeErrors: off grid polygon on layer M3dummy
114 0 offGridShapeErrors: off grid polygon on layer M4dummy
117 0 offGridShapeErrors: off grid polygon on layer M5dummy
120 0 offGridShapeErrors: off grid polygon on layer M6dummy
123 0 offGridShapeErrors: off grid polygon on layer Metal1
126 0 offGridShapeErrors: off grid polygon on layer Metal2
129 0 offGridShapeErrors: off grid polygon on layer Metal3
132 0 offGridShapeErrors: off grid polygon on layer Metal4
135 0 offGridShapeErrors: off grid polygon on layer Metal5
138 0 offGridShapeErrors: off grid polygon on layer Metal6
141 0 offGridShapeErrors: off grid polygon on layer NPNdummy
144 0 offGridShapeErrors: off grid polygon on layer Nburied
147 0 offGridShapeErrors: off grid polygon on layer Nimp
150 0 offGridShapeErrors: off grid polygon on layer Nwell
153 0 offGridShapeErrors: off grid polygon on layer Oxide
156 0 offGridShapeErrors: off grid polygon on layer PNPdummy
159 0 offGridShapeErrors: off grid polygon on layer Pimp
162 0 offGridShapeErrors: off grid polygon on layer Poly
165 0 offGridShapeErrors: off grid polygon on layer Pwell
168 0 offGridShapeErrors: off grid polygon on layer ResWdum
171 0 offGridShapeErrors: off grid polygon on layer Resdum
174 0 offGridShapeErrors: off grid polygon on layer ThickOxide
177 0 offGridShapeErrors: off grid polygon on layer Via1
180 0 offGridShapeErrors: off grid polygon on layer Via2
183 0 offGridShapeErrors: off grid polygon on layer Via3
186 0 offGridShapeErrors: off grid polygon on layer Via4
189 0 offGridShapeErrors: off grid polygon on layer Via5
191 0 non45 degree polygon on layer BJTdum
193 0 non45 degree polygon on layer Bondpad
195 0 non45 degree polygon on layer CapMetal
197 0 non45 degree polygon on layer Cont
199 0 non45 degree polygon on layer IND2dummy
201 0 non45 degree polygon on layer IND3dummy
203 0 non45 degree polygon on layer INDdummy
205 0 non45 degree polygon on layer JVAR1dummy
207 0 non45 degree polygon on layer JVAR2dummy
209 0 non45 degree polygon on layer JVAR3dummy
211 0 non45 degree polygon on layer M1dummy
213 0 non45 degree polygon on layer M2dummy
215 0 non45 degree polygon on layer M3dummy
217 0 non45 degree polygon on layer M4dummy
219 0 non45 degree polygon on layer M5dummy
221 0 non45 degree polygon on layer M6dummy
222 0 non45 degree polygon on layer Metal1
223 0 non45 degree polygon on layer Metal2
224 0 non45 degree polygon on layer Metal3
225 0 non45 degree polygon on layer Metal4
226 0 non45 degree polygon on layer Metal5
227 0 non45 degree polygon on layer Metal6
229 0 non45 degree polygon on layer NPNdummy
231 0 non45 degree polygon on layer Nburied
233 0 non45 degree polygon on layer Nimp
235 0 non45 degree polygon on layer Nwell
237 0 non45 degree polygon on layer Oxide
239 0 non45 degree polygon on layer PNPdummy
241 0 non45 degree polygon on layer Pimp
243 0 non45 degree polygon on layer Poly
245 0 non45 degree polygon on layer Pwell
247 0 non45 degree polygon on layer ResWdum
249 0 non45 degree polygon on layer Resdum
251 0 non45 degree polygon on layer ThickOxide
253 0 non45 degree polygon on layer Via1
255 0 non45 degree polygon on layer Via2
257 0 non45 degree polygon on layer Via3
259 0 non45 degree polygon on layer Via4
261 0 non45 degree polygon on layer Via5
262 0 acute angle on layer BJTdum
263 0 acute angle on layer IND2dummy
264 0 acute angle on layer IND3dummy
265 0 acute angle on layer INDdummy
266 0 acute angle on layer JVAR1dummy
267 0 acute angle on layer JVAR2dummy
268 0 acute angle on layer JVAR3dummy
269 0 acute angle on layer M1dummy
270 0 acute angle on layer M2dummy
271 0 acute angle on layer M3dummy
272 0 acute angle on layer M4dummy
273 0 acute angle on layer M5dummy
274 0 acute angle on layer M6dummy
275 0 acute angle on layer NPNdummy
276 0 acute angle on layer PNPdummy
277 0 acute angle on layer ResWdum
278 0 acute angle on layer Resdum
333 0 NWVIA_StampErrorFloat
334 0 NWVIA_StampErrorMult
340 0 NWELLterm_StampErrorFloat
341 0 NWELLterm_StampErrorMult
347 0 JVARterm_StampErrorFloat
348 0 JVARterm_StampErrorMult
354 0 JVARanode_StampErrorFloat
355 0 JVARanode_StampErrorMult
361 0 PWVIA_StampErrorFloat
362 0 PWVIA_StampErrorMult
368 0 Pwell_StampErrorFloat
369 0 Pwell_StampErrorMult
375 0 PWNBVIA_StampErrorFloat
376 0 PWNBVIA_StampErrorMult
382 0 ISOPWELL_StampErrorFloat
383 0 ISOPWELL_StampErrorMult
389 0 SUBVIA_StampErrorFloat
390 0 SUBVIA_StampErrorMult
396 0 PSUB_StampErrorFloat
397 0 PSUB_StampErrorMult
403 0 NBVIA_StampErrorFloat
404 0 NBVIA_StampErrorMult
410 0 Nburied_StampErrorFloat
411 0 Nburied_StampErrorMult
416 0 0A: Nburied width must be >= 1.0 um
418 0 0B: Nburied to Nburied spacing must be >= 1.0 um
419 0 1A: Nwell width must be >= 1.0 um
421 0 1B: Nwell to Nwell spacing must be >= 1.0 um
423 0 1C: Nburied to Nwell enclosure must be >= 0.3 um
424 0 1D: Pwell width must be >= 1.0 um
426 0 1E: Pwell to Pwell spacing must be >= 1.0 um
428 0 1F: Nburied to Pwell enclosure must be >= 0.3 um
430 0 1F: Nburied to Pwell enclosure must be >= 0.3 um
431 0 2A: Oxide width must be >= 0.4 um
433 0 2B: Oxide to Oxide spacing must be >= 0.3 um
435 0 2C: Nwell to Oxide enclosure must be >= 0.5 um
437 0 2C: Nwell to Oxide enclosure must be >= 0.5 um
439 0 2C: Pwell to Oxide enclosure must be >= 0.5 um
441 0 2C: Pwell to Oxide enclosure must be >= 0.5 um
443 0 2D: Nwell to Oxide spacing must be >= 0.5 um
444 0 2D: Nwell to Oxide spacing must be >= 0.5 um
446 0 2D: Pwell to Oxide spacing must be >= 0.5 um
447 0 2D: Pwell to Oxide spacing must be >= 0.5 um
448 0 2.5A: ThickOxide width must be >= 0.5 um
450 0 2.5B: ThickOxide to ThickOxide spacing must be >= 0.4 um
451 0 2.5D: ThickOxide to Oxide spacing must be >= 0.25 um
458 0 2.5E: ThickOxide to Poly spacing must be >= 0.4 um
459 0 2.5E: ThickOxide to Poly spacing must be >= 0.4 um
462 0 2.5F: ThickOxide to Poly enclosure must be >= 0.4 um
464 0 2.5F: ThickOxide to Poly enclosure must be >= 0.4 um
466 0 2.5C: ThickOxide to Oxide enclosure must be >= 0.25 um
467 0 3A: Nimp width must be >= 0.4 um
469 0 3B: Nimp to Nimp spacing must be >= 0.4 um
471 0 3C: Nimp to Oxide enclosure must be >= 0.2 um
473 0 3D: Nburied to Nimp enclosure must be >= 0.6 um
474 0 4A: Pimp width must be >= 0.4 um
476 0 4B: Pimp to Pimp spacing must be >= 0.4 um
478 0 4C: Pimp to Oxide enclosure must be >= 0.2 um
480 0 4D: Nburied to Pimp enclosure must be >= 0.6 um
481 0 5A: Poly width must be >= 0.18 um
483 0 5B: Poly to Poly spacing must be >= 0.3 um
485 0 5C: Poly to Oxide enclosure must be >= 0.2 um
487 0 5D: Oxide to Poly enclosure must be >= 0.4 um
488 0 5E: Oxide to Poly spacing must be >= 0.2 um
490 0 6B: Cont to Cont spacing must be >= 0.2 um
492 0 6A: Cont shapes must be 0.2x0.2 rectangles
494 0 6C: Oxide to Cont enclosure must be >= 0.2 um
496 0 6C: Oxide to Cont enclosure must be >= 0.2 um
499 0 6E: Poly to Cont spacing must be >= 0.2 um
500 0 6E: Poly to Cont spacing must be >= 0.2 um
502 0 6G: Nimp to Cont enclosure must be >= 0.1 um
504 0 6G: Nimp to Cont enclosure must be >= 0.1 um
509 0 6H: Oxide to Cont spacing must be >= 0.2 um
510 0 6H: Oxide to Cont spacing must be >= 0.2 um
512 0 6D: Poly to Cont enclosure must be >= 0.2 um
514 0 6D: Poly to Cont enclosure must be >= 0.2 um
516 0 6F: Pimp to Cont enclosure must be >= 0.1 um
518 0 6F: Pimp to Cont enclosure must be >= 0.1 um
519 0 7A: Metal1 width must be >= 0.3 um
521 0 7B: Metal1 to Metal1 spacing must be >= 0.3 um
523 0 7C: Metal1 to Cont enclosure must be >= 0.1 um
525 0 7C: Metal1 to Cont enclosure must be >= 0.1 um
526 0 9A: Metal2 width must be >= 0.3 um
528 0 9B: Metal2 to Metal2 spacing must be >= 0.3 um
530 0 9C: Metal2 to Via1 enclosure must be >= 0.1 um
532 0 9C: Metal2 to Via1 enclosure must be >= 0.1 um
533 0 11A: Metal3 width must be >= 0.3 um
535 0 11B: Metal3 to Metal3 spacing must be >= 0.3 um
537 0 11C: Metal3 to Via2NoCapInd enclosure must be >= 0.1 um
539 0 11C: Metal3 to Via2NoCapInd enclosure must be >= 0.1 um
540 0 15A: Metal4 width must be >= 0.3 um
542 0 15B: Metal4 to Metal4 spacing must be >= 0.3 um
544 0 15C: Metal4 to Via3 enclosure must be >= 0.1 um
546 0 15C: Metal4 to Via3 enclosure must be >= 0.1 um
547 0 17A: Metal5 width must be >= 0.3 um
549 0 17B: Metal5 to Metal5 spacing must be >= 0.3 um
551 0 17C: Metal5 to Via4 enclosure must be >= 0.1 um
553 0 17C: Metal5 to Via4 enclosure must be >= 0.1 um
554 0 19A: Metal6 width must be >= 0.3 um
556 0 19B: Metal6 to Metal6 spacing must be >= 0.3 um
558 0 19C: Metal6 to Via5 enclosure must be >= 0.1 um
560 0 19C: Metal6 to Via5 enclosure must be >= 0.1 um
562 0 8B: Via1 to Via1 spacing must be >= 0.3 um
564 0 8A: Via1 shapes must be 0.2x0.2 rectangles
566 0 8C: Metal1 to Via1 enclosure must be >= 0.1 um
568 0 8C: Metal1 to Via1 enclosure must be >= 0.1 um
570 0 10B: Via2 to Via2 spacing must be >= 0.3 um
572 0 10A: Via2 shapes must be 0.2x0.2 rectangles
574 0 10C: Metal2 to Via2 enclosure must be >= 0.1 um
576 0 10C: Metal2 to Via2 enclosure must be >= 0.1 um
578 0 14B: Via3 to Via3 spacing must be >= 0.3 um
580 0 14A: Via3 shapes must be 0.2x0.2 rectangles
582 0 14C: Metal3 to Via3 enclosure must be >= 0.1 um
584 0 14C: Metal3 to Via3 enclosure must be >= 0.1 um
586 0 16B: Via4 to Via4 spacing must be >= 0.3 um
588 0 16A: Via4 shapes must be 0.2x0.2 rectangles
590 0 16C: Metal4 to Via4 enclosure must be >= 0.1 um
592 0 16C: Metal4 to Via4 enclosure must be >= 0.1 um
594 0 18B: Via5 to Via5 spacing must be >= 0.3 um
596 0 18A: Via5 shapes must be 0.2x0.2 rectangles
598 0 18C: Metal5 to Via5 enclosure must be >= 0.1 um
600 0 18C: Metal5 to Via5 enclosure must be >= 0.1 um
602 0 12D: CapMetal to Metal3 enclosure must be >= 0.3 um
603 0 12A: CapMetal width must be >= 0.5 um
605 0 12B: Metal2 to Via2Cap enclosure must be >= 0.1 um
607 0 12B: Metal2 to Via2Cap enclosure must be >= 0.1 um
609 0 12C: CapMetal to Via2Cap enclosure must be >= 0.2 um
611 0 12C: CapMetal to Via2Cap enclosure must be >= 0.2 um
613 0 11D: Metal3 to Via2Cap enclosure must be >= 0.1 um
615 0 11D: Metal3 to Via2Cap enclosure must be >= 0.1 um
617 0 20C: Metal1 to Bondpad enclosure must be == 3.0 um
619 0 20C: Metal1 to Bondpad enclosure must be == 3.0 um
621 0 20D: Metal2 to Bondpad enclosure must be == 3.0 um
623 0 20D: Metal2 to Bondpad enclosure must be == 3.0 um
625 0 20E: Metal3 to Bondpad enclosure must be == 3.0 um
627 0 20E: Metal3 to Bondpad enclosure must be == 3.0 um
629 0 20F: Metal4 to Bondpad enclosure must be == 3.0 um
631 0 20F: Metal4 to Bondpad enclosure must be == 3.0 um
633 0 20G: Metal5 to Bondpad enclosure must be == 3.0 um
635 0 20G: Metal5 to Bondpad enclosure must be == 3.0 um
637 0 20H: Metal6 to Bondpad enclosure must be == 3.0 um
639 0 20H: Metal6 to Bondpad enclosure must be == 3.0 um
640 0 20A: Minimum Pad width = 45.0
642 0 20B: Minimum Pad spacing to Pad = 10.0
743 0 13A1: P+SD to NW tap spacing must be <= 10.0 um
846 0 13A2: N+SD to Iso Psub tap spacing must be <= 10.0 um
951 0 13A3: N+SD to Psub tap spacing must be <= 10.0 um
1054 0 13A3: N+SD to PW tap spacing must be <= 10.0 um
